### ISSUE TITLE
Default Breakpoints

### ISSUE THREAD

**Issue by loganfranken** [ucla-oarc-web/WebBlocks#114]
(Discussed in #103)

Although it is generally considered best practice for responsive layouts to adapt to _any_ viewport, it can sometimes be easier (from the standpoint of creating a generic framework) to establish a few standard breakpoints.

Examples from other frameworks:
- Bootstrap: http://twitter.github.com/bootstrap/scaffolding.html#responsive
- Skeleton: http://www.getskeleton.com/#mediaQueries

If we decide to use these standard breakpoints, the idea would be that some of the responsive aspects of our entities would be based around these breakpoints rather than the more "pure" responsive approach (let the element dynamically change based on the needs of the element's dimensions/content OR resize the browser until it looks bad, set a breakpoint, resize the browser until...).

I'm in favor of this approach as we can always choose the purer approach when appropriate, but use the standardized breakpoints as a fallback when necessary to avoid having a bunch of arbitrary media query breakpoints scattered around.

I realize this all sounds pretty academic, so let me give a brief example:

We are working on a "callout" element (#111): a smaller element that is floated either to the left or right and styled differently to "stand out" within a body of content. For example: a blockquote within a body of text (see: https://github.com/ucla/WebBlocks/blob/master/template/entity/blockquote/-ex-img-callout.png).

On smaller viewports, this callout should switch to span the full width of the container. The point at which this change needs to occur is more of an aesthetic concern than a technical matter, so in a "pure" responsive approach we would simply shrink the browser until it looks too stuffy and set a breakpoint.

This isn't really an option in a generic framework, however; it might be helpful, then, to design the callout element around these various breakpoints: we could decide that it flips over at the standardized 320px breakpoint, for example.

Also: I'm not a huge fan of them, but we could also provide utility classes like Bootstrap (`.visible-tablet`).

**Comment by ebollens** [comment]
I think my thoughts align with yours:
- For some elements, it makes sense to respond when necessary (like the nav bar should turn to a drop down when it overflows, not at some arbitrary size like it does in Bootstrap). There's some pretty simple overflow code that can detect this sort of thing.
- There are still some general use cases where breakpoints do make sense, such as with grids themselves. If someone is using our grid classes, they probably want to just get it to all go inline at some particular point (i.e.: how do we know how many words across a line is too few to have two columns?)

As a heads up, I've already kind of tackled this issue to some degree (although maybe we want to alter it):

From `/src/core/definitions/base/_variables.scss`:

``` css
$base-breakpoint-small: 768px !default;     /* width-based */
$base-breakpoint-medium: 978px !default;    /* width-based */
```

Then these classes in `/src/core/definitions/base/visibility/responsive/_hide.scss`:

``` css
.hide-small {
    @include -base-visibility-hide-small;
}

.hide-medium {
    @include -base-visibility-hide-medium;
}

.hide-large {
    @include -base-visibility-hide-large;
}
```

And these in `/src/core/definitions/base/visibility/responsive/_show.scss`:

``` css
.show-small {
    @include -base-visibility-show-small;
}

.show-medium {
    @include -base-visibility-show-medium;
}

.show-large {
    @include -base-visibility-show-large;
}
```

The implementations are based on these using media queries such as this:

``` css
@mixin -base-visibility-hide-small {

    @media screen and (max-width: $base-breakpoint-small - 1) {
        display: none;
    }

}

@mixin -base-visibility-hide-medium {

    @media screen and (min-width: $base-breakpoint-small) and (max-width: $base-breakpoint-medium - 1) {
        display: none;
    }

}

@mixin -base-visibility-hide-large {

    @media screen and (min-width: $base-breakpoint-medium) {
        display: none;
    }

}
```

Just showing an example of where I think breakpoints are useful - these sorts of utilities will definitely be used by users and I'd say we should bind them so that you get things like an inline set of elements instead of a grid at a certain breakpoint, since often you accompany an inline set of elements with some other UI elements you wouldn't show otherwise (hence the need for hide and show classes).

**Comment by alicetseng** [comment]
I'm in favor of both a default set of breakpoints for the grid and for utility hiding classes. The point of a grid framework is to get users 80% of the way there -- with the standard expectation that they should be adding their own customizations to taylor fit to their specific content needs. 

I think we're on the same page ... just one point:
I think that for the library to do this elegantly, the majority of the widths for the children elements should not be set on the entities themselves but, instead, be left up to the grid containers -- this approach works best for keeping the entities flexible and re-combinable -- and thus, really, when talking about default breakpoints, then we're mostly concerned with the grid itself. I believe most frameworks that use a responsive grid offload the widths to the grid and allow their children content entities to stretch to fill whatever grid-box is currently containing it. And the changes to the breakpoints from a responsive perspective depend on the grid as well.

For a small set of uber complex types -- (such as the nav bar) this may not prove feesible (and perhaps the callout is another) -- but I think for most of the other entities we can get away with a minimal approach. 

I'm in favor of taking a more minimal approach for default breakpoints and constraining it to the grid, leaving the specific entities w/o explicit width settings and only by a case-by-case situation (when an entity proves necessary) we explicitly define those breakpoint settings.

This way we don't get into a situation where we're making a tone of assumptions on layouts for entities -- and leaving that up to the template author to decide for themselves by judiciously choosing their grid cols.

**Comment by ebollens** [comment]
We also should try to keep the number of breakpoints small. I personally think two breakpoints (like the ones I established) are plenty. Any more and it starts getting confusing. That's a peeve of mine with Bootstrap, although I don't think we can normalize it :(

**Comment by alicetseng** [comment]
thoughts on this -- is there a way to define breakpoints as vars that a SASS user can change to their specs?

**Comment by ebollens** [comment]
Yes, there is. I've already done exactly this for our responsive visibility classes...

Here's the code definition itself:
https://github.com/ucla/WebBlocks/blob/master/src/core/definitions/base/visibility/responsive/_hide.scss

``` css
.hide-small {
    @include -base-visibility-hide-small;
}

.hide-medium {
    @include -base-visibility-hide-medium;
}

.hide-large {
    @include -base-visibility-hide-large;
}
```

You will note that there isn't actually anything responsive here. However, I wanted to show it for context. This is a core definition, for exactly this reason, because it defines semantics but doesn't do anything about implementation.

For implementation, let's refer to the core adapter.

Within the core adapter, here is where the breakpoints are defined thus far:
https://github.com/ucla/WebBlocks/blob/master/src/core/adapter/base/_variables.scss

``` css
$base-breakpoint-small:     768px !default;     /* width-based */
$base-breakpoint-medium:    978px !default;     /* width-based */
```

Then, they are used in the mixin definitions from the visibility core adapter implementation:
https://github.com/ucla/WebBlocks/blob/master/src/core/adapter/base/visibility/responsive/_hide.scss

``` css
@mixin -base-visibility-hide-small {

    @media screen and (max-width: $base-breakpoint-small - 1) {
        display: none;
    }

}

@mixin -base-visibility-hide-medium {

    @media screen and (min-width: $base-breakpoint-small) and (max-width: $base-breakpoint-medium - 1) {
        display: none;
    }

}

@mixin -base-visibility-hide-large {

    @media screen and (min-width: $base-breakpoint-medium) {
        display: none;
    }

}
```

So, yes, it's completely doable to use media queries in mixins. That is in fact why issue #92 was created (and resolved) which upgraded to SASS to version 3.2 where media query support for variable was added.
