### ISSUE TITLE
Rake with Debug Configs trigger error

### ISSUE THREAD

**Issue by alicetseng** [ucla-oarc-web/WebBlocks#128]
Hi @ebollens can you confirm this isn't user error on my part? It may very well be as I'm unfamiliar with all this syntax. 

Previously, with the old version of WebBlocks I was able to insert and save a config line in Rakefile-config.rb to produce an unminified css file for WebBlocks.

Here's the snippet: WebBlocks.config[:build][:debug][:enabled] = true

Following upgrade to the new version of WebBlocks (pulling latest code), after running rake --trace produces the following error messages in the consol:

itservices-mbp-atseng:WebBlocks atseng$ rake --trace
rake aborted!
undefined method `[]=' for false:FalseClass
./Rakefile-config.rb:21
/Users/atseng/Sites/WebBlocks/Rakefile:52:in`load'
/Users/atseng/Sites/WebBlocks/Rakefile:52
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in `load'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/rake_module.rb:25:in`load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:501:in `raw_load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:82:in`load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in `standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:81:in`load_rakefile'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:65:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:133:in`standard_exception_handling'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/lib/rake/application.rb:63:in `run'
/Library/Ruby/Gems/1.8/gems/rake-0.9.2.2/bin/rake:33
/usr/bin/rake:23:in`load'
/usr/bin/rake:23
itservices-mbp-atseng:WebBlocks atseng$

**Comment by ebollens** [comment]
@atsengucla can you please provide your config file?

**Comment by alicetseng** [comment]
sure here's what was in the config file:

```
# 
# WebBlocks Build Configuration File
# 
# This file may be used to override the default WebBlocks build configuration.
# 
# Eamples of configuration property redefinitions as follows:
#
#   WebBlocks.config[:build][:dir]      = 'build'
#   WebBlocks.config[:src][:adapter]    = 'bootstrap' or ['bootstrap', ...]
#   WebBlocks.config[:src][:modules]    = ['base', 'entity', ...] or [:all]
#   WebBlocks.config[:src][:extensions] = 'org' or ['org', ...]
#
# This file may also reside elsewhere in your filesystem, in which case Rake 
# should be passed a command-line property on invocation:
#
#   rake [command] -- --config=Rakefile-config.rb
#
# A full list of configurable attributes and their default values may be found 
# in rake/config.rb.
#
WebBlocks.config[:build][:debug][:enabled] = true
```

**Comment by ebollens** [comment]
Oh, I see the problem. It should be this:

``` ruby
WebBlocks.config[:build][:debug] = true
```

I announced this change when I updated the build architecture a few weeks back.

You can find a full list of configuration options here:
https://github.com/ucla/WebBlocks/blob/master/doc/Configuration.md

**Comment by alicetseng** [comment]
hmmmm. OK so the error stream is gone and I can run rake -- but I'm unable to locate the un-minified css files. Am I missing something? I get the minified versions out-putted but can't find the other set. Before these file would get outputted to the build directory -- was it just changed to another directory?

Just wanted to view the color entities in full CSS context (not SASS) so I could work on the hex values task.

**Comment by ebollens** [comment]
Oh the new builder just puts the unminified version in the place where the minified version would usually go. Is it not there?

**Comment by alicetseng** [comment]
Hi. nope. I'm not sure if I'm doing this wrong. Add script in config file. save. rerun rake. check build directory -- just have minified versions of css.

**Comment by ebollens** [comment]
@atsengucla, here's my config file:

``` ruby
WebBlocks.config[:build][:debug] = true
```

After I call `rake`, I end up with the file `build/css/blocks.css` uncompressed such that it reads like this:

``` css
/* line 18, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
article, aside, details, figcaption, figure, footer, header, hgroup, nav, section { display: block; }

/* line 27, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
audio, canvas, video { display: inline-block; *display: inline; *zoom: 1; }

/* line 36, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
audio:not([controls]) { display: none; }

/* line 43, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
html { font-size: 100%; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }

/* line 49, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
a:focus { outline: thin dotted #333; outline: 5px auto -webkit-focus-ring-color; outline-offset: -2px; }

/* line 54, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
a:hover, a:active { outline: 0; }

/* line 62, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
sub, sup { position: relative; font-size: 75%; line-height: 0; vertical-align: baseline; }

/* line 68, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
sup { top: -0.5em; }

/* line 71, ../../package/sass-twitter-bootstrap/lib/_reset.scss */
sub { bottom: -0.25em; }

//...
```
