### ISSUE TITLE
Header Element Spacing

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#173]
Headers have a top margin.

However, this can lead to a strange effect when they're the first element.

A fix might be viable with something like this:

``` css
h1, h2, h3, h4, h5, h6 {

    &:first-child {

        margin-top: 0;

    }

}
```

Undecided if this is worth it though, as it doesn't solve all cases. Another solution might be to avoid setting a top margin ever.

**Comment by ebollens** [comment]
Turns out that in the core adapter, we already do this:

(see `/src/core/adapter/base/type/_font.scss`)

``` css
    h1, h2, h3, h4, h5, h6 {
        &:first-child {
            margin-top: 0;
        }
    }
```

The problem with Bootstrap is that it doesn't set this case in `package/sass-twitter-bootstrap/lib/_type.scss`.

It can be resolved by adding the same definition to `@mixin -base-type-font` for the Bootstrap adapter:

``` css
    h1, h2, h3, h4, h5, h6 {
        &:first-child {
            margin-top: 0;
        }
    }
```

The caveat to this sort of approach is that it doesn't solve cases like these:

``` html
<div class="float-container">
    <img class="float-left">
    <h1>Title that should be top-aligned</h1>
    <p>Some textual content under the title</p>
    <h2>A subtitle that does have this spacing</h2>
    <p>Some textual content under the subtitle</p>
</div>
```

The hack that would solve this:

``` html
<div class="float-container">
    <img class="float-left">
    <div>
        <h1>Title that should be top-aligned</h1>
        <p>Some textual content under the title</p>
        <h2>A subtitle that does have this spacing</h2>
        <p>Some textual content under the subtitle</p>
    </div>
</div>
```

Just the sort of thing that someone handling markup might need to be aware of.
