### ISSUE TITLE
Bootstrap .container Uses Fixed Collapse Size

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#182]
Currently, the Bootstrap adapter `.container` is defined as : 

``` css
@mixin -base-structure-container {
    &:not(.bootstrap) {
        display: block;
        width: 100%;
        margin: auto;
        @if $structure-container-width-max {
            @media screen 
                and (max-width: $structure-container-width-max 
                                    + $structure-container-width-max 
                                        * (($structure-container-gutter*2)/100%) )
                and (min-width: 768px) /* body applies its own padding in bootstrap */
            {                                       
                width: 100% - ($structure-container-gutter*2);
                padding-left: $structure-container-gutter;
                padding-right: $structure-container-gutter;
            }
            max-width: $structure-container-width-max;
        } @else {
            @media screen 
                and (min-width: 768px) /* body applies its own padding in bootstrap */
            {                                       
                width: 100% - ($structure-container-gutter*2);
                padding-left: $structure-container-gutter;
                padding-right: $structure-container-gutter;
            }
        }
    }
}
```

Should not be using explicit widths.
