### ISSUE TITLE
Panel Min-Height

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#203]
Right now, if you use a panel but put nothing in it, then it doesn't actually get counted in the float. Need to come up with a way to handle this. An easy one is `min-height: 1px;` but it may not be fully portable.

**Comment by ebollens** [comment]
From http://www.dustindiaz.com/min-height-fast-hack/ ...

``` css
selector {
  min-height:1px;
  height:auto !important;
  height:1px;
}
```

From http://wellstyled.com/css-underscore-hack.html ...

``` css
selector {
   min-height: 1px;
   height: auto;
   _height: 1px;
}
```

I prefer the latter because it does not use `!important`, which has broader implications for the way that properties are set than just local to that one ruleset.
