### ISSUE TITLE
Superfluous Code in Button Core Adapter Implementation

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#212]
Currently, a number of rules like:

``` css
    &.primary:not(.text) {
        &:hover, &.active {
            background: $color-branding-primary-background-shadow;
            *background: darken($color-branding-primary-background-shadow, 5%);
        }
    }
```

The `:not(.text)` definition is no longer needed, as the text classes were turned to a prefixing scheme.
