### ISSUE TITLE
Accessible Invisible Text

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#268]
Labels and other sorts of HTML content are often necessary for accessibility, although they don't necessarily fit the page flow well. We should provide a class that leaves a piece of content visible to accessibility tools but hides it from general user browser view.

/CC @chris4ucla

**Comment by spiritcapsule** [comment]
when that text can be a focus target (a link for example), it should become clearly visible when it gains focus -- this is for the use case of a sighted keyboard-only user

**Comment by spiritcapsule** [comment]
skip links are the most common example of this

**Comment by ebollens** [comment]
A good article on options:
http://snook.ca/archives/html_and_css/hiding-content-for-accessibility

Snook's recommended approach ends up being:

``` css
.element-invisible {
  position: absolute !important;
  height: 1px; width: 1px; 
  overflow: hidden;
  clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
  clip: rect(1px, 1px, 1px, 1px);
}
```

Another one to consider is Boilerplate's `.visuallyhidden` class:

``` css
/* Hide only visually, but have it available for screenreaders: h5bp.com/v */
.visuallyhidden { border: 0; clip: rect(0 0 0 0); height: 1px; margin: -1px; overflow: hidden; padding: 0; position: absolute; width: 1px; }

/* Extends the .visuallyhidden class to allow the element to be focusable when navigated to via the keyboard: h5bp.com/p */
.visuallyhidden.focusable:active, .visuallyhidden.focusable:focus { clip: auto; height: auto; margin: 0; overflow: visible; position: static; width: auto; }
```
