### ISSUE TITLE
Allow Override of Special Mood Colors

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#282]
Right now, a few mood colors have "special" default assignments:

``` css
$color-branding-default-text-brightness: 5% !default;

$color-mood-inverse-background-light-brightness: 40% !default;
$color-mood-inverse-background-shadow-light-brightness: 30% !default;
$color-mood-inverse-light-border-brightness: 30% !default;

$color-mood-required: #a00 !default;
$color-mood-required-background-light-brightness: $color-background-light-brightness !default;
$color-mood-required-text-dark: $color-mood-required !default;
$color-mood-required-text-light: -color-generate-with-lightness(
                                        $color-mood-required,
                                        $color-mood-required-background-light-brightness
                                 ) !default;
$color-mood-required-background-light-brightness: 100% !default;
$color-mood-required-background-shadow-light-brightness: 95% !default;
$color-mood-required-foreground-text:    -color-generate-with-lightness(
                                                $color-mood-required, 
                                                $color-text-brightness
                                        ) !default;
$color-mood-required: #d8d8d8;
```

We need a mechanism for making sure that these are only set if the user hasn't redefined their base.

A mixin like this one might help:

``` css
@mixin my_mixin() {
  /* Set the variable to null only if it's not already set. */
  $base-color: null !default;

  /* Check the guaranteed-existing variable. If it didn't exist 
   * before calling this mixin/function/whatever, this will 
   * return false. */
  @if $base-color {
     color: $base-color;
  }
}
```

This comes from here: 
http://stackoverflow.com/questions/8512802/checking-if-a-variable-is-defined-in-sass
