### ISSUE TITLE
IE7 Image Scaling

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#379]
Quick and easy snippet to improve IE 7 image scaling:

``` css
img { -ms-interpolation-mode: bicubic; }
```

We're not officially supporting IE7, but at the same time, we are doing "best effort", and the cost of this is small enough, almost certainly worth it.
