### ISSUE TITLE
IE9 SVG Bug

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#380]
There's an overflow bug in IE9 around SVG. Fix is trivial:

``` css
svg:not(:root) { overflow: hidden; }
```
