### ISSUE TITLE
Implementation of .hide-accessible

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#460]
@hyperboy is using the following for the `.element-invisible` and `.element-invisible.element-focusable` elements in Open Framework:

``` css
.element-invisible {
    position: absolute !important;
    clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
    clip: rect(1px, 1px, 1px, 1px);
}
.element-invisible.element-focusable:active,
.element-invisible.element-focusable:focus {
    position: static !important;
    clip: auto;
    overflow: visible;
    height: auto;
    padding: 0 1em;
}
```

Unless I'm mistaken, these are meant to be accessible but hidden by default, the latter being visible if focused on. If this is correct, it's the same purpose as our `.hide-accessible` and `.focusable` classes.

Our implementation to date is as follows:

``` css
@mixin -base-visibility-hide-accessible {
    position: absolute; 
    overflow: hidden; 
    height: 1px; 
    width: 1px;
    padding: 0; 
    border: 0; 
    margin: -1px; 
    clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
    clip: rect(1px, 1px, 1px, 1px);
}

@mixin -base-visibility-hide-accessible-focusable {
    &:active, &:focus { 
        position: static; 
        overflow: visible; 
        height: auto; 
        width: auto; 
        margin: 0; 
        clip: auto; 
    }
}
```

I'm curious if we can simplify our implementation to use the implementation from Open Framework instead - does it cover what we're trying to do or is there an edge case? They seem roughly the same except that ours has a bunch of extra jazz. I cannot find any previous discussion that explains our extra complexity.
