### ISSUE TITLE
Nonsensical .container box-model when % gutters

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#461]
Right now, the `.container` is defined as:

``` css
@mixin -base-structure-container {
    display: block;
    width: 100%;
    margin: auto;
    @if $structure-container-width-max {
        @media screen 
            and (max-width: $structure-container-width-max 
                                + $structure-container-width-max 
                                    * (($structure-container-gutter*2)/100%) )
            and (min-width: $breakpoint-small+1)
        {                                       
            width: 100% - ($structure-container-gutter*2);
            padding-left: $structure-container-gutter;
            padding-right: $structure-container-gutter;
        }
        max-width: $structure-container-width-max;
    } @else {
        @media screen 
            and (min-width: $breakpoint-small+1)
        {                                       
            width: 100% - ($structure-container-gutter*2);
            padding-left: $structure-container-gutter;
            padding-right: $structure-container-gutter;
        }
    }
    @media screen and (max-width: $breakpoint-small) {
        width: auto;
        padding-left: ($structure-container-gutter/100%) * $breakpoint-small; 
        padding-right: ($structure-container-gutter/100%) * $breakpoint-small; 
    }
}
```

However, this leads to a confusing behavior if you go `position:relative` on the container and then try to place a `position:absolute` element within, in that it exceeds the container dimensions. This is because the box model treats padding as internal to the box. I therefore suggest changing the gutters to be based on `margin` instead:

``` css
@mixin -base-structure-container {
    display: block;
    width: 100%;
    margin: auto;
    @if $structure-container-width-max {
        @media screen 
            and (max-width: $structure-container-width-max 
                                + $structure-container-width-max 
                                    * (($structure-container-gutter*2)/100%) )
            and (min-width: $breakpoint-small+1)
        {                                       
            width: 100% - ($structure-container-gutter*2);
            padding-left: $structure-container-gutter;
            padding-right: $structure-container-gutter;
        }
        max-width: $structure-container-width-max;
    } @else {
        @media screen 
            and (min-width: $breakpoint-small+1)
        {                                       
            width: 100% - ($structure-container-gutter*2);
            margin-left: $structure-container-gutter;
            margin-right: $structure-container-gutter;
        }
    }
    @media screen and (max-width: $breakpoint-small) {
        width: auto;
        margin-left: ($structure-container-gutter/100%) * $breakpoint-small; 
        margin-right: ($structure-container-gutter/100%) * $breakpoint-small; 
    }
}
```

This cropped up when working with the search box in the UCLA IT Services Plone theme /CC @albertwu @melcassio @uncleerniebs
