### ISSUE TITLE
IE 6-7 Hack for .hide-accessible

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#462]
Right now, `hide-accessible` is implemented as:

``` css
@mixin -base-visibility-hide-accessible {
    position: absolute; 
    overflow: hidden; 
    height: 1px; 
    width: 1px;
    padding: 0; 
    border: 0; 
    margin: -1px; 
    clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
    clip: rect(1px, 1px, 1px, 1px);
}
```

Why bother letting newer browsers choke on the IE hack? Let's add the `*` to the IE 7 ad below fix to deliver it only there:

``` css
@mixin -base-visibility-hide-accessible {
    position: absolute; 
    overflow: hidden; 
    height: 1px; 
    width: 1px;
    padding: 0; 
    border: 0; 
    margin: -1px; 
    clip: rect(1px, 1px, 1px, 1px);
    *clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
}
```

IE will choke on the first `clip`, but the second it will understand.
