### ISSUE TITLE
Minification Stage in Compile

### ISSUE THREAD

**Issue by ebollens** [ucla-oarc-web/WebBlocks#57]
Right now, we minify the CSS twice, one with `compass` via the configuration setting `output_style = :compressed` and then also with `uglifycss`. It's probably not right to be doing this twice.

Interestingly, stacking the two minifiers together yields the best results.

Here were the outcomes:
- No Minification: 202074
- Minification with `compass`: 110035
- Minifiation with `uglifycss`: 109295
- Minification with both `compass` and `uglifycss`: 109217

While stacking them is okay in some ways, I'm actually leaning towards minifying only with `uglifycss` because then we get the expanded source file as well. For debug purposes, this is invaluable as it actually includes where the definition lives with lines like these:

``` css
/* line 46, ../../package/sass-twitter-bootstrap/lib/_labels-badges.scss */
.label-success[href], .badge-success[href] {
  background-color: #356635;
}
```

``` css
/* line 13, ../../src/core/definitions/base/type/align.scss */
.text-justify {
  text-align: justify;
}
```

``` css
/* line 6, ../../src/adapter/bootstrap/entity/nav/_bar.scss */
nav.bar.top, nav.bar.bottom {
  position: absolute;
  left: 0;
  right: 0;
}
```

Need to figure out the right way to improve this.
